// We define the exact instructions for the AI. This is called the System Prompt.
// It acts as the unchangeable operating manual for the model, ensuring absolute consistency.
const SYSTEM_PROMPT = `You are an expert customer support triager. 
Analyze the following email text and classify it into exactly one of these categories: Bug, Billing, Feature, Hacker (when it is obvious) or Other.
You must also provide a short, one sentence summary of the issue.
You must respond ONLY with a valid JSON object containing exactly two keys: "category" and "summary" and try not to show the whole below the summary and category.`;

// This is the main function that communicates with the Groq servers.
// It takes the cleaned text from our unboxing machine and the secret keys from our config file.
export async function classifyEmail(text, config) {
  
  // We define the destination URL for the Groq API.
  const url = "https://api.groq.com/openai/v1/chat/completions";
  
  // We use a character code trick here to build the header key.
  // This evaluates to the standard Content Type header required for sending JSON data.
  const m = String.fromCharCode(45);
  const headerContentType = "Content" + m + "Type";
  
  const headers = {
    "Authorization": "Bearer " + config.groqApiKey
  };
  headers[headerContentType] = "application/json";

  // We assemble the data payload exactly how the OpenAI standard requires it.
  const payload = {
    model: config.groqModel,
    // Setting temperature to 0 means the AI will be highly deterministic and logical.
    // It removes all creative randomness, which is exactly what we want for categorization.
    temperature: 0,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: text }
    ],
    // This strict format forces the Groq API to return raw JSON instead of conversational text.
    response_format: { type: "json_object" }
  };

  try {
    // We send the HTTP POST request to Groq and pause our code until the server responds.
    const response = await fetch(url, {
      method: "POST",
      headers: headers,
      body: JSON.stringify(payload)
    });

    // If the server throws a red flag (like a rate limit or an expired key), we catch it immediately.
    // This prevents the code from trying to read empty data later.
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error("Groq API Error: " + response.status + " " + errorText);
    }

    // We unpack the raw network response into a readable JavaScript object.
    const data = await response.json();
    
    // We drill down into the deeply nested response structure to extract the exact text generated by the AI.
    const aiMessage = data.choices[0].message.content;
    
    // The AI string is mathematically formatted as JSON, so we parse it into a real JavaScript object.
    return JSON.parse(aiMessage);
    
  } catch (error) {
    // The Safety Net: If the AI connection fails completely, we do not want the whole pipeline to crash.
    // We log the error for the developer to see, and return a safe fallback object.
    // This ensures the email still gets pushed to Slack, just with an Error tag instead of a real category.
    console.error("AI Classification failed:", error.message);
    return { category: "Error", summary: "Failed to classify email due to AI network error." };
  }
}